name: Build and Push Base image

on :
  push:
    branches:
      - master
  schedule:
    - cron: 00 02 * * *
  workflow_dispatch:


jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: amirulandalib
          password: ${{ secrets.GH_TOKEN }}
      - name: Build Base images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ghcr.io/amirulandalib/desterroku:latest
